spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/homework_email
    username: user
    password: pass

  flyway:
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate

  security:
    user:
      name: admin
      password: 123456
    

logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  port: 8081
