spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/homework_email
    username: user
    password: pass

  flyway:
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8081
